In [11]:

import pandas as pd
df = pd.DataFrame()
df = pd.read_csv('Preços semestrais - AUTOMOTIVOS_2025.01.csv', sep =';', encoding = 'latin1')
df

C:\Users\danilo.bastos\AppData\Local\Temp\ipykernel_3100\1108933872.py:3: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Preços semestrais - AUTOMOTIVOS_2025.01.csv', sep =';', encoding = 'latin1')

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df_produtoe = df.loc[df['Produto'] == 'ETANOL']
df_produtoe

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
3,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,5.19,NaN,R$ / litro,RAIZEN
7,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,ETANOL,01/01/2025,5.29,NaN,R$ / litro,RAIZEN
11,NE,CE,SOBRAL,CENTER POSTO COMERCIAL LTDA,02.905.892/0001-03,AVENIDA JOSE ARIMATEIA MONTE E SILVA,425,NaN,CAMPOS DOS VELHOS,62114-000,ETANOL,01/01/2025,5.29,NaN,R$ / litro,VIBRA
15,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0001-54,AVENIDA MONSENHOR JOSE ALOISIO PINTO,80,LOJA 01,DOM EXPEDITO,62050-255,ETANOL,01/01/2025,5.29,NaN,R$ / litro,IPIRANGA
19,NE,CE,SOBRAL,POSTO SAO DOMINGOS LTDA,69.366.128/0001-70,AVENIDA DOUTOR GUARANI,854,NaN,JOCELY DANTAS DE ANDRADE TORRES,62042-030,ETANOL,01/01/2025,5.29,NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420391,NE,PE,BELO JARDIM,AUTO POSTO GARANHUNS LTDA,70.065.800/0003-38,AVENIDA OSCAR PEREIRA DA SILVA,364,NaN,SANTO ANTONIO,55152-110,ETANOL,30/06/2025,4.36,NaN,R$ / litro,BRANCA
420395,NE,PE,BELO JARDIM,POSTO CENTRO LTDA,54.096.194/0001-08,PRACA CAPITAO TOMAS FERREIRA,SN,NaN,CENTRO,55150-130,ETANOL,30/06/2025,4.36,NaN,R$ / litro,LARCO
420399,S,PR,CASCAVEL,POSTO PARAVIS LTDA,03.358.802/0002-47,RUA PARANA,4560,NaN,CENTRO,85810-011,ETANOL,30/06/2025,4.47,NaN,R$ / litro,VIBRA
420404,NE,BA,SERRINHA,COMERCIO DE COMBUSTIVEIS VEREDAS LTDA,54.003.912/0001-46,RODOVIA BA 409,151 A,QUADRAD LOTE 09,NOVO HORIZONTE - 01,48700-000,ETANOL,30/06/2025,4.65,NaN,R$ / litro,BRANCA
420408,S,RS,ALVORADA,POSTO DE COMBUSTIVEIS DEA LTDA,03.299.835/0002-63,AVENIDA PRES GETULIO VARGAS,2725,NaN,MARINGA,94810-002,ETANOL,30/06/2025,4.39,NaN,R$ / litro,BRANCA

In [20]:
df_gas = df.loc[df['Produto'] == 'GASOLINA']
df_gas

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÃS DO BRASIL DIST. DERIV. DE PET. BIOC....,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
8,NE,CE,SOBRAL,CENTER POSTO COMERCIAL LTDA,02.905.892/0001-03,AVENIDA JOSE ARIMATEIA MONTE E SILVA,425,NaN,CAMPOS DOS VELHOS,62114-000,GASOLINA,01/01/2025,"6,69",NaN,R$ / litro,VIBRA
12,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0001-54,AVENIDA MONSENHOR JOSE ALOISIO PINTO,80,LOJA 01,DOM EXPEDITO,62050-255,GASOLINA,01/01/2025,"6,69",NaN,R$ / litro,IPIRANGA
16,NE,CE,SOBRAL,POSTO SAO DOMINGOS LTDA,69.366.128/0001-70,AVENIDA DOUTOR GUARANI,854,NaN,JOCELY DANTAS DE ANDRADE TORRES,62042-030,GASOLINA,01/01/2025,"6,69",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420389,NE,PE,BELO JARDIM,AUTO POSTO GARANHUNS LTDA,70.065.800/0003-38,AVENIDA OSCAR PEREIRA DA SILVA,364,NaN,SANTO ANTONIO,55152-110,GASOLINA,30/06/2025,"5,70",NaN,R$ / litro,BRANCA
420392,NE,PE,BELO JARDIM,POSTO CENTRO LTDA,54.096.194/0001-08,PRACA CAPITAO TOMAS FERREIRA,SN,NaN,CENTRO,55150-130,GASOLINA,30/06/2025,"5,70",NaN,R$ / litro,LARCO
420396,S,PR,CASCAVEL,POSTO PARAVIS LTDA,03.358.802/0002-47,RUA PARANA,4560,NaN,CENTRO,85810-011,GASOLINA,30/06/2025,"6,49",NaN,R$ / litro,VIBRA
420400,NE,BA,SERRINHA,COMERCIO DE COMBUSTIVEIS VEREDAS LTDA,54.003.912/0001-46,RODOVIA BA 409,151 A,QUADRAD LOTE 09,NOVO HORIZONTE - 01,48700-000,GASOLINA,30/06/2025,"5,99",NaN,R$ / litro,BRANCA
420405,S,RS,ALVORADA,POSTO DE COMBUSTIVEIS DEA LTDA,03.299.835/0002-63,AVENIDA PRES GETULIO VARGAS,2725,NaN,MARINGA,94810-002,GASOLINA,30/06/2025,"6,05",NaN,R$ / litro,BRANCA

In [60]:
df_gas = df.loc[df['Produto'] == 'GASOLINA']
df_municipios = df.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipios

                  Municipio  Valor de Venda
0                ABAETETUBA        6.337510
1                ACAILANDIA        6.071692
2                ADAMANTINA        5.566915
3     AGUAS LINDAS DE GOIAS        5.968274
4                ALAGOINHAS        5.576432
..                      ...             ...
403  VITORIA DE SANTO ANTAO        5.500092
404           VOLTA REDONDA        5.990214
405              VOTORANTIM        5.740694
406             VOTUPORANGA        5.493773
407                 XANXERE        6.241707

[408 rows x 2 columns]

In [52]:
df_municipios= df.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipios

                  Municipio  Valor de Venda
0                ABAETETUBA        6.337510
1                ACAILANDIA        6.071692
2                ADAMANTINA        5.566915
3     AGUAS LINDAS DE GOIAS        5.968274
4                ALAGOINHAS        5.576432
..                      ...             ...
403  VITORIA DE SANTO ANTAO        5.500092
404           VOLTA REDONDA        5.990214
405              VOTORANTIM        5.740694
406             VOTUPORANGA        5.493773
407                 XANXERE        6.241707

[408 rows x 2 columns]

In [62]:
df_gas = df.loc[df['Produto'] == 'GASOLINA']
df_municipios = df_municipios.sort_values(by = 'Valor de Venda')
df_municipios

           Municipio  Valor de Venda
44             BAURU        5.230309
142         GOIATUBA        5.306387
23        ARARAQUARA        5.323278
216             LINS        5.350204
188          JACAREI        5.368833
..               ...             ...
35              BAGE        7.004844
6           ALENQUER        7.160152
307       RIO BRANCO        7.181965
115  CRUZEIRO DO SUL        7.784926
269        PARINTINS        8.293551

[408 rows x 2 columns]

In [ ]:
df_mun = df_mun.sort_values(by = 'Cep')